name: dartzz
version: 0.2.1
description: A library for typed functional programming, inspired by Scala Cats and Kotlin Arrow

environment:
  sdk: ">=2.6.0 <3.0.0"


dev_dependencies:
    pedantic: ^1.0.0
    test: ^1.0.0