name: dartzz_core
version: 0.3.0
description: A library for typed functional programming, inspired by Scala Cats and Kotlin Arrow

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.2.3
  dartzz_meta:
    path: ../meta


dev_dependencies:
    pedantic: ^1.0.0
    test: ^1.0.0
    build_runner: ^1.8.0

    dartzz_gen:
      path: ../gen