name: dartzz_gen_test
version: 0.3.0
description: Tests for source code generators for dartzz - a library for typed functional programming, inspired by Scala Cats and Kotlin Arrow

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  source_gen: ^0.9.5
  analyzer: ^0.39.4
  build_config: ^0.4.2
  build: ^1.2.2

  dartzz_meta:
    path: ../meta

  dartzz_gen:
    path: ../gen

dev_dependencies:
    pedantic: ^1.0.0
    test: ^1.0.0
    build_runner: ^1.8.0